---
    name: CI - release
    on:
        push:
            tags:
                - 'v*'

    jobs:
        releases:
            name: Create release
            runs-on: ubuntu-latest
            permissions:
                contents: write
            steps:
                - uses: actions/checkout@v4

                - name: Create release
                  uses: softprops/action-gh-release@v2
                  with:
                    body: |
                      Calyptia Core Frontend release for ${{ github.ref_name }} version
                    generate_release_notes: true
